### ISSUE TITLE
Get rid of "-g" parameter

### ISSUE THREAD

**Issue by vloux** [Tharos-ux/pangraphs#1]
Sniff the GFA format version in the header of the GFA file

**Comment by Tharos-ux** [comment]
Fixed in commit https://github.com/Tharos-ux/pangraphs/commit/ed870c826ef172686dc53e8d5b282ba1a5380a31. WARNING : requires update of lib with `pip install gfagraphs --upgrade` (lib ver. 0.1.71, commit https://github.com/Tharos-ux/gfatypes/commit/769f72138af6efe9cf32dc494af25e6a5fbb71e4)

New function `get_gfa_subtype` in `workspace.main` evaluates the gfa subversion for each file given as argument and feeds the information to the functions, plus it tries to evaluate if file exists/is valid...

Evaluation relies on the existence of a header line
However, if version is not specified in header, but a header exists, the type "unknown" will be set.
If no header is in file, worst-case scenario will be assumed (rGFA) as H-lines are not present in rGFA but should be present in any other GFA format, according to [gfa-spec](https://github.com/GFA-spec/GFA-spec).
